version: "3"
services:
  ormond-chore-mgr:
    build: 
      context: ./ormond-chores/
    volumes: 
      - ./ormond-chores:/proj
      - /etc/localtime:/etc/localtime
    restart: on-failure

  chess960-scheduler:
    build:
      context: ./chess960-scheduler/bin/
    volumes:
      - ./chess960-scheduler/src:/src
      - /etc/localtime:/etc/localtime
    restart: on-failure

  portainer:
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"

volumes:
  portainer_data: